name: dart_application_1
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  font_awesome_flutter: ^10.5.0
  stateless: ^0.1.1
  flutter:
   assets:  
    - lib\assets\images\download.png
 

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
